### ISSUE TITLE
As a data engineer, I need to make example queries for the new MOZ location data, so that users can explore it

### ISSUE THREAD

**Issue by mwigham** [beeldengeluid/comunica-web-client#38]
Tasks:
- [x] Develop SPARQL queries for persons and concerts associated with locations
- [x] Add these queries to the comunica client

Acceptance criteria:
- [x] A linked data user can use the queries in the client

**Comment by wmelder** [comment]
Apparently some of these quereis were already published on the client. It turns out some of these queries are not exactly right and aren't doing what they should do. At least that's what came out of this [issue](https://github.com/beeldengeluid/x-omgeving/issues/767) 
@mwigham Could you assess the location queries that use labels and improve according to hints mentioned in the above issue ? Please let me know if it is not clear.

**Comment by mwigham** [comment]
queries fixed and deployed
